/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/HgPigz9Eh6D
 */
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar";

import { CornerDownLeft, Mic, Paperclip } from "lucide-react";

import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip";
import { ScrollArea } from "@/components/ui/scroll-area";

export function Chat() {
  return (
    <div
      className="chat-messages"
      // style={{ maxHeight: "100%", overflowY: "auto" }}
    >
      {/* <div className="w-full overflow-auto h-full flex flex-col" style={{ }}>
    <div className="p-4 overflow-y-scroll"> */}
      <div className="flex flex-col space-y-4 mb-16">
        <div className="flex items-start space-x-2">
          <Avatar>
            <AvatarImage alt="User" src="/placeholder.svg?height=40&width=40" />
            <AvatarFallback>U</AvatarFallback>
          </Avatar>
          <div className="flex-1">
            <div className="message rounded-t-lg rounded-br-lg p-3">
              <div className="flex justify-between items-center mb-1">
                <span>
                  <strong>You</strong>
                </span>
                <div className="flex space-x-1">
                  <PencilIcon className="text-blue-500" />
                  <MicIcon className="text-blue-500" />
                  <XIcon className="text-red-500" />
                </div>
              </div>
              <p className="mb-1">What's the weather like today?</p>
              <p className="text-sm text-gray-400">¿Cómo está el clima hoy?</p>
            </div>
          </div>
        </div>
        <div className="flex items-start space-x-2 justify-end">
          <div className="flex-1">
            <div className="message rounded-t-lg rounded-bl-lg p-3">
              <div className="flex justify-between items-center mb-1">
                <span>
                  <strong>Glot</strong>
                </span>
                <div className="flex space-x-1">
                  <MicIcon className="text-blue-500" />
                </div>
              </div>
              <p className="mb-1">
                ¡Claro! ¿Quieres probar alguna especialidad de la casa o
                necesitas recomendaciones sobre nuestro menú? ¡Estoy aquí para
                ayudarte!
              </p>
              <p className="text-sm text-gray-400">
                Sure! Do you want to try some speciality in the house or do you
                need recommendations on our menu? I'm here to help you!
              </p>
            </div>
          </div>
          <div className="flex justify-between items-center mb-1">
            <Avatar>
              <AvatarImage
                alt="Glot"
                src="/placeholder.svg?height=40&width=40"
              />
              <AvatarFallback>G</AvatarFallback>
            </Avatar>
          </div>
        </div>

        <div className="flex items-start space-x-2">
          <Avatar>
            <AvatarImage alt="User" src="/placeholder.svg?height=40&width=40" />
            <AvatarFallback>U</AvatarFallback>
          </Avatar>
          <div className="flex-1">
            <div className="message rounded-t-lg rounded-br-lg p-3">
              <div className="flex justify-between items-center mb-1">
                <span>
                  <strong>You</strong>
                </span>
                <div className="flex space-x-1">
                  <PencilIcon className="text-blue-500" />
                  <MicIcon className="text-blue-500" />
                  <XIcon className="text-red-500" />
                </div>
              </div>
              <p className="mb-1">What's the weather like today?</p>
              <p className="text-sm text-gray-400">¿Cómo está el clima hoy?</p>
            </div>
          </div>
        </div>
        <div className="flex items-start space-x-2 justify-end">
          <div className="flex-1">
            <div className="message rounded-t-lg rounded-bl-lg p-3">
              <div className="flex justify-between items-center mb-1">
                <span>
                  <strong>Glot</strong>
                </span>
                <div className="flex space-x-1">
                  <MicIcon className="text-blue-500" />
                </div>
              </div>
              <p className="mb-1">
                ¡Claro! ¿Quieres probar alguna especialidad de la casa o
                necesitas recomendaciones sobre nuestro menú? ¡Estoy aquí para
                ayudarte!
              </p>
              <p className="text-sm text-gray-400">
                Sure! Do you want to try some speciality in the house or do you
                need recommendations on our menu? I'm here to help you!
              </p>
            </div>
          </div>
          <div className="flex justify-between items-center mb-1">
            <Avatar>
              <AvatarImage
                alt="Glot"
                src="/placeholder.svg?height=40&width=40"
              />
              <AvatarFallback>G</AvatarFallback>
            </Avatar>
          </div>
        </div>

        <div className="flex items-start space-x-2">
          <Avatar>
            <AvatarImage alt="User" src="/placeholder.svg?height=40&width=40" />
            <AvatarFallback>U</AvatarFallback>
          </Avatar>
          <div className="flex-1">
            <div className="message rounded-t-lg rounded-br-lg p-3">
              <div className="flex justify-between items-center mb-1">
                <span>
                  <strong>You</strong>
                </span>
                <div className="flex space-x-1">
                  <PencilIcon className="text-blue-500" />
                  <MicIcon className="text-blue-500" />
                  <XIcon className="text-red-500" />
                </div>
              </div>
              <p className="mb-1">What's the weather like today?</p>
              <p className="text-sm text-gray-400">¿Cómo está el clima hoy?</p>
            </div>
          </div>
        </div>
        <div className="flex items-start space-x-2 justify-end">
          <div className="flex-1">
            <div className="message rounded-t-lg rounded-bl-lg p-3">
              <div className="flex justify-between items-center mb-1">
                <span>
                  <strong>Glot</strong>
                </span>
                <div className="flex space-x-1">
                  <MicIcon className="text-blue-500" />
                </div>
              </div>
              <p className="mb-1">
                ¡Claro! ¿Quieres probar alguna especialidad de la casa o
                necesitas recomendaciones sobre nuestro menú? ¡Estoy aquí para
                ayudarte!
              </p>
              <p className="text-sm text-gray-400">
                Sure! Do you want to try some speciality in the house or do you
                need recommendations on our menu? I'm here to help you!
              </p>
            </div>
          </div>
          <div className="flex justify-between items-center mb-1">
            <Avatar>
              <AvatarImage
                alt="Glot"
                src="/placeholder.svg?height=40&width=40"
              />
              <AvatarFallback>G</AvatarFallback>
            </Avatar>
          </div>
        </div>

        <div className="flex items-start space-x-2">
          <Avatar>
            <AvatarImage alt="User" src="/placeholder.svg?height=40&width=40" />
            <AvatarFallback>U</AvatarFallback>
          </Avatar>
          <div className="flex-1">
            <div className="message rounded-t-lg rounded-br-lg p-3">
              <div className="flex justify-between items-center mb-1">
                <span>
                  <strong>You</strong>
                </span>
                <div className="flex space-x-1">
                  <PencilIcon className="text-blue-500" />
                  <MicIcon className="text-blue-500" />
                  <XIcon className="text-red-500" />
                </div>
              </div>
              <p className="mb-1">What's the weather like today?</p>
              <p className="text-sm text-gray-400">¿Cómo está el clima hoy?</p>
            </div>
          </div>
        </div>
        <div className="flex items-start space-x-2 justify-end">
          <div className="flex-1">
            <div className="message rounded-t-lg rounded-bl-lg p-3">
              <div className="flex justify-between items-center mb-1">
                <span>
                  <strong>Glot</strong>
                </span>
                <div className="flex space-x-1">
                  <MicIcon className="text-blue-500" />
                </div>
              </div>
              <p className="mb-1">
                ¡Claro! ¿Quieres probar alguna especialidad de la casa o
                necesitas recomendaciones sobre nuestro menú? ¡Estoy aquí para
                ayudarte!
              </p>
              <p className="text-sm text-gray-400">
                Sure! Do you want to try some speciality in the house or do you
                need recommendations on our menu? I'm here to help you!
              </p>
            </div>
          </div>
          <div className="flex justify-between items-center mb-1">
            <Avatar>
              <AvatarImage
                alt="Glot"
                src="/placeholder.svg?height=40&width=40"
              />
              <AvatarFallback>G</AvatarFallback>
            </Avatar>
          </div>
        </div>
      </div>

      {/* Chat Input */}
      <div className="sticky bottom-10">
        <form className="overflow-hidden rounded-lg border bg-background focus-within:ring-1 focus-within:ring-ring">
          <Label htmlFor="message" className="sr-only">
            Message
          </Label>
          <Textarea
            id="message"
            placeholder="Type your message here..."
            className="min-h-12 resize-none border-0 p-3 shadow-none focus-visible:ring-0"
          />
          <div className="flex items-center p-3 pt-0">
            <TooltipProvider>
              <Tooltip>
                <TooltipTrigger asChild>
                  <Button variant="ghost" size="icon">
                    <Paperclip className="size-4" />
                    <span className="sr-only">Attach file</span>
                  </Button>
                </TooltipTrigger>
                <TooltipContent side="top">Attach File</TooltipContent>
              </Tooltip>
            </TooltipProvider>
            <TooltipProvider>
              <Tooltip>
                <TooltipTrigger asChild>
                  <Button variant="ghost" size="icon">
                    <Mic className="size-4" />
                    <span className="sr-only">Use Microphone</span>
                  </Button>
                </TooltipTrigger>
                <TooltipContent side="top">Use Microphone</TooltipContent>
              </Tooltip>
            </TooltipProvider>
            <Button type="submit" size="sm" className="ml-auto gap-1.5">
              Send Message
              <CornerDownLeft className="size-3.5" />
            </Button>
          </div>
        </form>
      </div>

      {/* <div className="mt-6">
        <div className="flex items-center message rounded-lg p-2">
          <PlaneIcon className="text-blue-500" />
          <input
            className="flex-1 bg-transparent border-none placeholder-gray-400 focus:ring-0 text-white p-2"
            placeholder="Write your message to Glot..."
            type="text"
          />
          <MicIcon className="text-blue-500" />
        </div>
      </div> */}
    </div>
  );
}

function PencilIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M17 3a2.85 2.83 0 1 1 4 4L7.5 20.5 2 22l1.5-5.5Z" />
      <path d="m15 5 4 4" />
    </svg>
  );
}

function MicIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 2a3 3 0 0 0-3 3v7a3 3 0 0 0 6 0V5a3 3 0 0 0-3-3Z" />
      <path d="M19 10v2a7 7 0 0 1-14 0v-2" />
      <line x1="12" x2="12" y1="19" y2="22" />
    </svg>
  );
}

function XIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  );
}

function PlaneIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M17.8 19.2 16 11l3.5-3.5C21 6 21.5 4 21 3c-1-.5-3 0-4.5 1.5L13 8 4.8 6.2c-.5-.1-.9.1-1.1.5l-.3.5c-.2.5-.1 1 .3 1.3L9 12l-2 3H4l-1 1 3 2 2 3 1-1v-3l3-2 3.5 5.3c.3.4.8.5 1.3.3l.5-.2c.4-.3.6-.7.5-1.2z" />
    </svg>
  );
}
